name: Test suite
permissions:
  contents: read

on:
  push:
  pull_request:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Unify cypress cache folder to avoid missing binaries on macOS/Windows
  CYPRESS_CACHE_FOLDER: ~/.cypress-cache

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Formatting
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "24"
      - run: corepack enable
      - run: pnpm install

      - run: pnpm exec prettier --check .

  typechecks:
    runs-on: ubuntu-latest
    name: Typechecks
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "24"
      - run: corepack enable
      - run: pnpm install

      - run: pnpm exec tsc

  e2e-chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "24"
      - run: corepack enable

      - uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6
        with:
          browser: chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    name: E2E on Firefox
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "24"
      - run: corepack enable

      - uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6
        with:
          browser: firefox

  e2e-edge:
    runs-on: windows-latest
    name: E2E on Edge
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "24"
      - run: corepack enable

      - uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6
        with:
          browser: edge

  e2e-safari:
    runs-on: macos-latest
    name: E2E on WebKit
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "24"
      - run: corepack enable

      - uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6
        with:
          browser: webkit
